version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    ports:
      - "3606:3606"
    volumes:
      - ./mysql_data:/var/lib/mysql

  django:
    container_name: django-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - .:/code
    command: sh -c "sleep 30 && ./manage.py runserver 0.0.0.0:8000"

volumes:
  mysql_data: 


